/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import com.mycompany.version2.Handlers.GameHandler;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Tobias Mouer
 */
public class GameWindow extends javax.swing.JFrame {

    GameHandler gh;
    private final String handScore = "Hand score: ", title = "BlackJack";

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        gh = new GameHandler();
        initComponents();
        setTitle(title);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 4 - this.getSize().width / 4, dim.height / 4 - this.getSize().height / 4);
        winnerText.setVisible(false);
        playersHandText.setText(gh.addCards(1, 2));
        playerValueText.setText(handScore + gh.getValue(1));
        dealersHandText.setText(gh.addCards(0, 1));
        dealersValueText.setText(handScore + gh.getValue(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextCardButton = new javax.swing.JButton();
        Info1Text = new javax.swing.JLabel();
        playerValueText = new javax.swing.JLabel();
        stopButton = new javax.swing.JButton();
        winnerText = new javax.swing.JLabel();
        Info2Text = new javax.swing.JLabel();
        dealersValueText = new javax.swing.JLabel();
        playerScroll = new javax.swing.JScrollPane();
        playersHandText = new javax.swing.JTextArea();
        dealerScroll = new javax.swing.JScrollPane();
        dealersHandText = new javax.swing.JTextArea();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nextCardButton.setText("Hit me!");
        nextCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextCardButtonMouseClicked(evt);
            }
        });
        nextCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCardButtonActionPerformed(evt);
            }
        });

        Info1Text.setText("Your cards are:");

        playerValueText.setText("Hand score: ");

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        winnerText.setForeground(new java.awt.Color(255, 0, 0));
        winnerText.setText("the winner is");

        Info2Text.setText("Dealers card(s) are:");

        dealersValueText.setText("Hand score: ");

        playersHandText.setColumns(20);
        playersHandText.setRows(5);
        playerScroll.setViewportView(playersHandText);

        dealersHandText.setColumns(20);
        dealersHandText.setRows(5);
        dealerScroll.setViewportView(dealersHandText);

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(winnerText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nextCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton))
                    .addComponent(Info1Text)
                    .addComponent(playerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerValueText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Info2Text)
                        .addGap(148, 148, 148))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(resetButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dealerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dealersValueText)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Info2Text, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Info1Text))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerValueText)
                    .addComponent(dealersValueText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextCardButton)
                    .addComponent(stopButton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(winnerText)
                    .addComponent(resetButton))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextCardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextCardButtonMouseClicked

    }//GEN-LAST:event_nextCardButtonMouseClicked

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        gh.startDealerTurn();
        dealersHandText.setText(gh.getPlayerHand(0).toString());
        dealersValueText.setText(handScore + gh.getValue(0));
        winnerText.setText(gh.calculateHands(gh.getPlayer(0), gh.getPlayer(1)));
        winnerText.setVisible(true);
        nextCardButton.setEnabled(false);
        stopButton.setEnabled(false);
    }//GEN-LAST:event_stopButtonActionPerformed

    private void nextCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCardButtonActionPerformed
        playersHandText.setText(gh.addCards(1, 1));
        String value = gh.getValue(1);
        playerValueText.setText(handScore + value);
        int score = Integer.parseInt(value);
        if (score >= 21) {
            stopButtonActionPerformed(evt);
        }
    }//GEN-LAST:event_nextCardButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        this.dispose();
        new GameWindow().setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Info1Text;
    private javax.swing.JLabel Info2Text;
    private javax.swing.JScrollPane dealerScroll;
    private javax.swing.JTextArea dealersHandText;
    private javax.swing.JLabel dealersValueText;
    private javax.swing.JButton nextCardButton;
    private javax.swing.JScrollPane playerScroll;
    private javax.swing.JLabel playerValueText;
    private javax.swing.JTextArea playersHandText;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel winnerText;
    // End of variables declaration//GEN-END:variables
}
