/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphics;

import com.mycompany.version2.Handlers.GameHandler;

/**
 *
 * @author Tobias Mouer
 */
public class GameWindow extends javax.swing.JFrame {

    GameHandler gh;
    private final String handScore = "Hand score: ", title = "BlackJack";

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        gh = new GameHandler();
        initComponents();
        setTitle(title);
        winnerText.setVisible(false);
        playersHandText.setText(gh.addCards(1, 2));
        playerValueText.setText(handScore + gh.getValue(1));
        dealersHandText.setText(gh.addCards(0, 1));
        dealersValueText.setText(handScore + gh.getValue(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextCardButton = new javax.swing.JButton();
        Info1Text = new javax.swing.JLabel();
        playerValueText = new javax.swing.JLabel();
        stopButton = new javax.swing.JButton();
        winnerText = new javax.swing.JLabel();
        Info2Text = new javax.swing.JLabel();
        dealersValueText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playersHandText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        dealersHandText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nextCardButton.setText("Hit me!");
        nextCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextCardButtonMouseClicked(evt);
            }
        });
        nextCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextCardButtonActionPerformed(evt);
            }
        });

        Info1Text.setText("Your cards are:");

        playerValueText.setText("Hand score: ");

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        winnerText.setText("jLabel1");

        Info2Text.setText("Dealers card(s) are:");

        dealersValueText.setText("Hand score: ");

        playersHandText.setColumns(20);
        playersHandText.setRows(5);
        jScrollPane1.setViewportView(playersHandText);

        dealersHandText.setColumns(20);
        dealersHandText.setRows(5);
        jScrollPane2.setViewportView(dealersHandText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(winnerText)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nextCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton))
                    .addComponent(Info1Text)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerValueText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Info2Text)
                    .addComponent(dealersValueText))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Info1Text)
                    .addComponent(Info2Text))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerValueText)
                    .addComponent(dealersValueText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextCardButton)
                    .addComponent(stopButton))
                .addGap(37, 37, 37)
                .addComponent(winnerText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextCardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextCardButtonMouseClicked

    }//GEN-LAST:event_nextCardButtonMouseClicked

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        winnerText.setText(gh.CalculateHands(gh.getPlayer(0), gh.getPlayer(1)));
        winnerText.setVisible(true);
    }//GEN-LAST:event_stopButtonActionPerformed

    private void nextCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextCardButtonActionPerformed
        playersHandText.setText(gh.addCards(1, 1));
        playerValueText.setText(handScore + gh.getValue(1));
    }//GEN-LAST:event_nextCardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Info1Text;
    private javax.swing.JLabel Info2Text;
    private javax.swing.JTextArea dealersHandText;
    private javax.swing.JLabel dealersValueText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextCardButton;
    private javax.swing.JLabel playerValueText;
    private javax.swing.JTextArea playersHandText;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel winnerText;
    // End of variables declaration//GEN-END:variables
}
